/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Astronaut.glb 
*/

import React, { useEffect, useRef } from 'react'
import { MeshTransmissionMaterial, useAnimations, useFBX, useGLTF } from '@react-three/drei'

export function Astronaut(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('models/Astronaut.glb')

  const {animations: sadWalk} = useFBX('animations/sad-walk.fbx');

  sadWalk[0].name = "sad-walk";

  const {actions} = useAnimations(sadWalk, group);

  useEffect(() => {
    actions["sad-walk"].reset().play();
  }, [actions])

  const materialProps = {
    thickness: 0.2,
    roughness: 0,
    transmission: 1,
    ior: 1.2,
    chromaticAberration: 0.02,
    backside: true,
  }

  return (
    <group {...props} ref={group} dispose={null} onClick={props.onClick}>
      <group rotation-x={-Math.PI / 2}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh geometry={nodes.Body_1.geometry} material={materials.flag} skeleton={nodes.Body_1.skeleton} />
        <skinnedMesh geometry={nodes.Body_2.geometry} skeleton={nodes.Body_2.skeleton}>
          <MeshTransmissionMaterial {...materialProps} />
        </skinnedMesh>
        <skinnedMesh geometry={nodes.Body_3.geometry} skeleton={nodes.Body_3.skeleton}>
          <MeshTransmissionMaterial {...materialProps} />
        </skinnedMesh>
        <skinnedMesh geometry={nodes.Helmet_1.geometry} skeleton={nodes.Helmet_1.skeleton}>
          <MeshTransmissionMaterial {...materialProps} />
        </skinnedMesh>
        <skinnedMesh geometry={nodes.Helmet_2.geometry} material={materials.transparent_mask} skeleton={nodes.Helmet_2.skeleton} />
      </group>
    </group>
  );
}

useGLTF.preload('models/Astronaut.glb')

{/* <group {...props} dispose={null}>
      <primitive object={nodes.mixamorigHips} />
      <skinnedMesh geometry={nodes.Body_1.geometry} material={materials.flag} skeleton={nodes.Body_1.skeleton} />
      <skinnedMesh geometry={nodes.Body_2.geometry} material={materials.white} skeleton={nodes.Body_2.skeleton} />
      <skinnedMesh geometry={nodes.Body_3.geometry} material={materials.gray} skeleton={nodes.Body_3.skeleton} />
      <skinnedMesh geometry={nodes.Helmet_1.geometry} material={materials.white} skeleton={nodes.Helmet_1.skeleton} />
      <skinnedMesh geometry={nodes.Helmet_2.geometry} material={materials.transparent_mask} skeleton={nodes.Helmet_2.skeleton} />
    </group> */}